### ISSUE TITLE
Long Run Time

### ISSUE THREAD

**Issue by rensa** [heroldn/climpact2#1]
Running test.climpact2.r with climpact2 0.1 on Blizzard (R 3.0.3) and it's still running after 25 minutes. I'll leave it going for now but I assume this is unexpected.
```
> source("test.climpact2.r")
Loading required package: PCICt
[1] "Time coordinate in hours, converting to seconds..."
[1] "********* CALCULATING INDICES"
```

**EDIT:** concluded after about 45--50 minutes with the file `txx.CLIMPACT.climpact_test.1950.2009.nc` created:
```
[1] "WORKING ON IRREGULAR GRID"
[1] "climdex.txx completed."
> 
```

**Comment by heroldn** [comment]
This occurs as the index is being calculated over the whole spatial domain as opposed to a single lat/lon. Hopefully we'll get a parallel version of all this going in the future.
