### ISSUE TITLE
Test name Sensible_bounds_temp

### ISSUE THREAD

**Issue by lisavalexander** [heroldn/climpact2#12]
Check error message appears if temperature is greater than 100degC or less than -100degC and is not missing but calculation continues

**Comment by tammasloughran** [comment]
This is a copy of issue https://github.com/heroldn/climpact2/issues/5 . It still hasn't been addressed in the latest version.

**Comment by heroldn** [comment]
Temperature bounds are tested for time series data. But not for netCDF data. I will leave this for a later date.

**Comment by heroldn** [comment]
I'm going to close this. Code now exists to test implausible temp and precip values.
