### ISSUE TITLE
Test name Correct_units

### ISSUE THREAD

**Issue by lisavalexander** [heroldn/climpact2#15]
Tests units are appropriate for the variables specified, possibly do conversions if are of incorrect but common type

**Comment by tammasloughran** [comment]
I manually changed the units attribute in my AWAP files to deg F. The indices calculated from files that contain deg F and deg C are exactly the same which means there is no unit conversion happening.

**Comment by tammasloughran** [comment]
I also changed the units attribute to "the wrong units" and it still works, so it doesn’t even check if the units are valid.
I also get a bunch of notes:
```
Note: no visible binding for '<<-' assignment to 'nc_tsmin' 
Note: no visible binding for global variable 'nc_tsmin' 
Note: no visible binding for global variable 'nc_tsmin' 
Note: no visible binding for '<<-' assignment to 'nc_tsmax' 
Note: no visible binding for global variable 'nc_tsmax' 
Note: no visible binding for global variable 'nc_tsmax' 
Note: no visible binding for '<<-' assignment to 'nc_prec' 
Note: no visible binding for global variable 'nc_prec' 
Note: no visible binding for global variable 'nc_prec' 
Note: no visible binding for global variable 'nc_tsmin' 
Note: no visible binding for global variable 'nc_tsmax' 
Note: no visible binding for '<<-' assignment to 'cio' 
Note: no visible global function definition for 'cicompile' 
Note: no visible binding for '<<-' assignment to 'cio' 
Note: no visible binding for '<<-' assignment to 'cio'
```
Not sure what they mean, perhaps the attributes are not being read correctly?

**Comment by heroldn** [comment]
Kelvin and Fahrenheit will now be changed to Celcius. And meters or centimeters will be changed to mm for precip.
The code won't check the units attribute though against a "legitimate list". There could be too many variations I think (e.g. C, degC, <deg symbol>C, celcius...).
