### ISSUE TITLE
Test name Irregular_grids

### ISSUE THREAD

**Issue by lisavalexander** [heroldn/climpact2#16]
Tests that software can deal with irregular grids such as NARCliM

**Comment by tammasloughran** [comment]
This is one of my tests. NARCLiM is the default dataset that has been used throughout my own testing. The output using this definitely contains a description of the irregular grid, so I wont bother testing that again. Instead, I thought it would be good to try a dataset that isn't gridded at all. An example that I use is ACORNSAT, its 112 time series of station data. I've already downloaded it from bom and converted it into a more manageable netcdf file for my own work. I used CF conventions to describe the data, see chapter 9 of http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#discrete-sampling-geometries . I used an incomplete multidimensional array representation, ie. data has two dimensions, time and station, with nans where timeseries are incomplete.
When I run this through climpact it complains that there are not enough dimensions.
test script:
```
minfilename = "/srv/ccrc/data35/z5032520/ACORNSAT/daily/ACORNSAT.nc"
maxfilename = "/srv/ccrc/data35/z5032520/ACORNSAT/daily/ACORNSAT.nc"

climpact.loader(
#precfile=precfilename,
tsminfile=minfilename,
tsmaxfile=maxfilename,
#precname="pracc_fl",
tsminname="tmin",
tsmaxname="tmax",
indices=indices,
time_format = "%Y%m%d",
write_quantiles=FALSE,
cores=4,
baserange=c(1961,1990),
identifier="Irregular_grids")
```

And the climapact whinge:
```
[1] "***************************************"
[1] "********* CALCULATING INDICES *********"
[1] "***************************************"
[1] "diag: index call:  array(indexcompile(cio,freq=\"monthly\"))"
Warning in e$fun(obj, substitute(ex), parent.frame(), e$data) :
  already exporting variable(s): indices, precqtiles_tmp, tempqtiles_tmp, a, baserange, indexparam, lon, quantile_file, test
Note: no visible global function definition for 'hargreaves' 
Note: no visible global function definition for 'spei' 
Note: no visible global function definition for 'spi' 
Note: no visible binding for global variable 'j' 
Note: no visible binding for global variable 'j' 
Note: no visible binding for '<<-' assignment to 'tminqtiles_array' 
Note: no visible binding for '<<-' assignment to 'tmaxqtiles_array' 
Note: no visible binding for '<<-' assignment to 'tavgqtiles_array' 
Note: no visible binding for global variable 'j' 
Note: no visible binding for '<<-' assignment to 'precipqtiles_array' 
Note: no visible binding for '<<-' assignment to 'cio' 
Error in { : task 1 failed - "incorrect number of dimensions"
Calls: climpact.loader -> %dopar% -> <Anonymous>
Execution halted
```

So, is it within the scope of climpact to support ungridded station data?

**Comment by heroldn** [comment]
Thanks Tammas, cc'ing Lisa here. So the climpact function you're testing is
meant to deal with gridded netcdf files. Time series of ascii data will/can
be handled through the GUI. But I don't think we'd planned on time series
in a netcdf file that wasn't on a lat/lon grid. In other words it assumes
your data is on a lat/lon grid.

I suppose in the future the function could be fooled into doing this by
creating an empty grid with data at the one point the user provides, but
that would be future work.

Cheers

Nick.

**Comment by tammasloughran** [comment]
Yeah, or it could be reshaped into an arbitrarily sized 3 dimensional array and then reshaped back to its original form afterwards. For example ACORNSAT data could go from 26785x112 to 26785x56x2 and back.

**Comment by heroldn** [comment]
Definitely, in that case though I'd probable prefer to just put a check in
there to see if it's not a lat/lon dataset somehow, even if it's a flag
from the user.

Cheers

Nick.

**Comment by lisavalexander** [comment]
Yep agree that this is one to go into 'future work'. Main thing for this test was to check that climpact could handle NARCLiM data (which it seems to have done fine in other tests).
