### ISSUE TITLE
Test name Tabs_and_spaces

### ISSUE THREAD

**Issue by lisavalexander** [heroldn/climpact2#23]
Tests that software can handle tabs and comma-delimited files as well as spaces (ascii input)

**Comment by tammasloughran** [comment]
Comma-delimited files are not handled correctly. Similar error to issue https://github.com/heroldn/climpact2/issues/25
```
> Error in scan(file, what, nmax, sep, dec, quote, skip, nlines, na.strings,  : 
  scan() expected 'a real', got '1910,01,01,-99.9,36.9,7.8'
```

**Comment by tammasloughran** [comment]
Spacing using tabs works fine.

**Comment by heroldn** [comment]
Comma-delimited files should be ok now. Since only one type of delimiter can be chosen (space in this instance) all files will now be scanned for commas and replaced with a TAB (will be treated as a space). Takes a few seconds.
