### ISSUE TITLE
Test name Characters_in_nums

### ISSUE THREAD

**Issue by lisavalexander** [heroldn/climpact2#25]
Tests whether input data contains characters where there should be numbers

**Comment by tammasloughran** [comment]
For the GUI this type of mistake will cause problems at the point when text file is read into the program. It expects the data in the text file to be structured in a particular manner and if it sees a character when it expects a real number it throws the following error and the QC interface doesn't even start.
```
> Error in scan(file, what, nmax, sep, dec, quote, skip, nlines, na.strings,  : 
  scan() expected 'a real', got '1r'
```
I guess this is not such bad behaviour as it does ultimately prevent errors but it would be tedious to fix the errors one at a time and then reload the file into the program to find the next one.

**Comment by heroldn** [comment]
Related to one of the other issues. The GUI will now return a message box showing the error and referring the user to the manual for the correct formatting requirements for the text file. The program doesn't exit and the user can select another file (or fix their problem file and retry).

This doesn't show what line the error occurs at though. I think this is a future task if really necessary.
