### ISSUE TITLE
Additional test for WSDI/CSDI

### ISSUE THREAD

**Issue by lisavalexander** [heroldn/climpact2#30]
Need to check that WSDI is identical to WSDI6 (and not identical to WSDI2,3,4,5 etc). What is the max value that WSDI can take. Same tests for CSDI.

**Comment by tammasloughran** [comment]
For ASCII I calculated both wsdi and wsdin with n specified as 6. Did a diff of the resulting files and the only difference was the headers. I repeated for wsdin with n=2 and the whole files are different. Same thing for csdi too. So all okay.
