### ISSUE TITLE
Netcdf files that have incliomplete years halt execution.

### ISSUE THREAD

**Issue by tammasloughran** [heroldn/climpact2#32]
This isn’t really a big issue but if you use a netCDF whose record period does not end on the 31st of December then you will have in your index output files a series of blank records for the rest of the incomplete year. Climpact2 then throws an error complaining that there are not enough values for the incomplete year and execution stops.

**Comment by tammasloughran** [comment]
Oh and this is the whinge:
```
Error in ncvar_put(tmpout, time_bndscdf, aperm(month_time_bnds, c(2, 1))) : 
  ncvar_put: error: you asked to write 1224 values, but the passed data array only has 1202 entries!
```

**Comment by heroldn** [comment]
Hi Tammas, I'm tentatively marking this as done. But would you mind checking this functionality again. The code should be able to take a dataset that is incomplete (i.e. doesn't end on the 31st December of some year). This is kinda crucial. There should be fields of NA in the remaining months of the last year of the dataset. Please reopen or open another issue if this doesn't work. Cheers.
