### ISSUE TITLE
Test #4: No errors returned for insane data

### ISSUE THREAD

**Issue by tammasloughran** [heroldn/climpact2#5]
There were no errors returned during [test number 4](https://github.com/heroldn/climpact2/wiki/Tests). The resulting files had no missing values in the regions with the dodgy data, just unusual numbers. For example 365 or 0 for indices that count days, large values of daily temperature range. Threshold based indices are unaffected since the same quantity was added to the original data through time (except for the ehf heatwave metrics).

How should data that exceeds these sensible bounds be handled? Fill it with missing values?

**Comment by heroldn** [comment]
Closing this as code now checks if temp/prec are outside physical values and returns an appropriate error if so (conversion from Kelvin and Fahrenheit is done before this if necessary).
