### ISSUE TITLE
Test #4: Indices that returned errors

### ISSUE THREAD

**Issue by tammasloughran** [heroldn/climpact2#6]
Some indices returned errors during [test number 4](https://github.com/heroldn/climpact2/wiki/Tests). 
hdheat, cddcold, gddgrow all returned this error:
```
[1] "diag: index call:  array(indexcompile(cio))"
Note: no visible binding for global variable '.Data' 
Note: no visible binding for global variable '.Data' 
Error: any(ci@data$tavg > Tbarr) is not TRUE
Execution halted
```
Is this error because of the test data or its a problem with the indices themselves?

**Comment by heroldn** [comment]
Hi Tammas

Thanks I know about this. It's just a problem with the default value I've
chosen for Tbarr. Not sure what to set it to. So you can avoid that index
for now.

Cheers

Nick.
