### ISSUE TITLE
index.master.list: rnnmm missing and r20mm repeated

### ISSUE THREAD

**Issue by StefanContractor** [heroldn/climpact2#7]
I tried running test.climpact2.r with all 27 etccdi indices but got the error:

Error in climpact.loader(precfile = precfilename, tsminfile = minfilename,  :
  One or more indices are unknown. See XX for list.
Execution halted

On comparision with the index.master.list I found that the index rnnmm which has a default threshold of 1mm was missing and r20mm occurred twice.

I deleted rnnmm from test.climpact2.r and the program is running okay.

**Comment by heroldn** [comment]
Thanks Stefan. Corrected.
