### ISSUE TITLE
Can we compute the thresholds for precipitation only?

### ISSUE THREAD

**Issue by bonfils2** [heroldn/climpact2#76]
I am not interested in the temperature extremes from now but i need the precipitation thresholds:
If I use:

library(climdex.pcic.ncdf)
# list of one to three input files. e.g. c("a.nc","b.nc","c.nc")
input.files = c("./sample_data/climpact2.sampledata.gridded.1991-2010.nc")

# list of variable names according to above file(s)
vars=c(prec="precip")

# output file name
output.file = "./output/thresholds.1991-1997.nc"

# author data
author.data=list(institution="My University", institution_id="MU")

# reference period
base.range=c(1991,1997)

# number of cores to use (or FALSE)
parallel = FALSE

# print messages?
verbose=TRUE

I obtain: 
Loading required package: PCICt
Loading required package: lmomco
Loading required package: parallel
Loading required package: ggplot2
# Package SPEI (1.7) loaded [try SPEINews()].
Error in y[[d$q.path]] : no such index at level 1
Calls: create.thresholds.from.file ... write.thresholds.data -> lapply -> FUN -> t -> sapply -> lapply -> FUN
Execution halted

Of course, all is well if I used: vars=c(tmax="tmax", tmin="tmin", prec="precip") and not vars=c(prec="precip")

Thanks!

**Comment by heroldn** [comment]
This is something that needs to be changed in climpact. In the meantime a workaround is to just feed bogus tmax/tmin data in (e.g. copy your precip data twice and name it tmax/tmin), then simply ignore any output related to temperature. Not ideal but should work.
